---
title: 'Project 1: Exploratory Data Analysis'
author: "SDS348"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Hannah Palacios, hfp225

## Data Wrangling and Data Exploration


```{R}
library(tidyverse)
library(ggplot2)
library(cluster)

data1 <- read_csv("College.csv") 
# https://www.kaggle.com/smithashivakumar/college
data2 <- read_csv("salary_potential.csv") 
# https://www.kaggle.com/jessemostipak/college-tuition-diversity-and-pay?select=salary_potential.csv

```
### Introduction

*The datasets I chose are called "College" and "Salary Potential", and they were both acquired through the "Kaggle" website. The College dataset comes from the book "An Introduction to Statistical Learning" by James et al. 2013. It contains 19 columns: X1 = school name, Private = yes if private and no if public, Apps = number of applications received, Accept = number of applicants accepted, Enroll = number of new students enrolled, Top10perc = number of new students from top 10% of high school, Top25perc = number of new students from top 25% high school, F.Undergrad = number of full time undergraduates, P.Undergrad = number of part time undergraduates, Outstate = out of state tuition, Room.Board = costs of room and board, Books = estimated book costs, Personal = estimated personal spending, PhD = percent of faculty with PhD, Terminal = percent of faculty with terminal degree, S.F.Ration = student faculty ratio, perc. alumni = Percent of alumni who donate, Expend = instructional expenditure per student, Grad.rate = graduation rate.*

*The Salary Potential dataset originally came from the US Department of Education, but more specifically from a site called payscale.com. It contains 7 columns: rank = potential salary rank within state, name = school name, state_name = state name, early_career_pay = estimated early career pay in USD, mid_career_pay = estimated mid career pay in USD, make_world_better_percent = percent of alumni that think they are making world better place, stem_percent = percent of student body in STEM. These datasets are interesting to me because they both have some variables that are not commonly known, for example I was interested by the percent of alumni who think they are making a difference in the world, and the estimated personal spending for different schools. I expect there to be an association between the Private/public status of a school and the early or mid career estimated pay. I am also curious if there will be an association between the student faculty ratio and the percent of alumni who think they are making the world a better place.*

### Merging

```{R}
merged_data <- inner_join(data1, data2, by=c("X1"="name")) 
merged_data2 <- merged_data %>% rename(College_name = X1)
merged_data2 %>% glimpse
```

*I chose to do an inner join because I only wanted to keep schools that were found in both datasets, so the schools found in only 1 of the 2 datasets were dropped. This way, during wrangling there would not be rows with many NAs. Additionally, there were enough schools in common between the 2 datasets that keeping only the matching ones still left me with 332 observations which was plenty for my analysis. One potential problem with dropping the non-matches is that the joined dataset may not be fully representative of all the schools in each state.* 

### Wrangling and tidying

```{R}

# filter
merged_data2 %>% filter(Private == "Yes" & mid_career_pay >= 100000) %>% n_distinct("College_name")
merged_data2 %>% filter(Private == "No" & mid_career_pay >= 100000) %>% n_distinct("College_name")

# arrange
merged_data2 %>% arrange(desc(Expend),desc(Grad.Rate)) %>% glimpse

# group_by
merged_data2 %>% group_by(state_name) %>% summarize(mean(make_world_better_percent)) %>% head(n=10)

# mutate
merged_data2 <- merged_data2 %>% mutate(Accept_rate = (Accept/Apps)*100) 

merged_data2 <- merged_data2 %>% mutate(Total_cost = Room.Board + Books + Personal)

merged_data2 <- merged_data2 %>% mutate(category_accept_rate = case_when(Accept_rate >= 0 & Accept_rate <= 25 ~ "Quartile 1", Accept_rate > 25 & Accept_rate <= 50 ~ "Quartile 2", Accept_rate > 50 & Accept_rate <= 75 ~ "Quartile 3", Accept_rate > 75 & Accept_rate <= 100 ~ "Quartile 4"))

# select
merged_data2 %>% dplyr::select(College_name, Accept_rate, Enroll) %>% arrange(desc(Accept_rate)) %>% head(n=10)

# summarize:
merged_data2 %>% summarise(mean(early_career_pay)) 
merged_data2 %>% summarise(sd(Top10perc))
merged_data2 %>% summarise(median(P.Undergrad)) 
merged_data2 %>% summarise(IQR(Expend))
merged_data2 %>% summarise(quantile(perc.alumni,0.97))
merged_data2 %>% summarise(var(Terminal))
merged_data2 %>% summarise(max(stem_percent))
merged_data2 %>% group_by(Private) %>% summarise_all(n_distinct)

# summarizing with group_by, and pivoting
merged_data2 %>% group_by(state_name) %>% summarise(mean_roomboard = mean(Room.Board), mean_books = mean(Books), mean_personal = mean(Personal)) %>% pivot_longer(c(mean_roomboard, mean_books, mean_personal), names_to = "Type of expense", values_to = "Cost") %>% head(n=10)

merged_data2 %>% group_by(state_name, Private) %>% summarise(min_outstate_tuition = min(Outstate)) %>% pivot_wider(names_from = "Private", values_from = "min_outstate_tuition") %>% head(n=10)
```

*Filtering the data revealed that there were 100 private schools, yet only 17 public schools that had an estimated mid-career pay rate greater than $100,000. Although the data presents only an estimation of mid career pay and major/degree likely has a large effect on this mid-career pay, this result still surprised me. I was curious as to whether the school's educational expenditure per-student would affect the graduation rate, so I arranged the data by descending expenditure and graduation rate. It does not seem that the highest educational expenditures lead to the highest graduation rates. I grouped the data by state and then summarized the mean percent of alumni who think they're making the world a better place. For mutate, I created a column for acceptance rate by dividing number of students accepted by the number of applications, then multiplied by 100. I also created a column called Total_cost that shows the estimated student costs (aside from tuition) for books, personal expenses, and room/board by summing these columns together. I also created a columnn that categorizes acceptance rate into 4 different bins. I used select to show college names, their acceptance rates, and the number of students enrolled that year.*

*For summary statistics, I found that the mean estimated early career pay for colleges in this dataset was $52,837. Having 54% of alumni who still donate would put a college in the 97th percentile for this category. I grouped the data by private/public status and found there were many more private schools in this dataset than public. The maximum percent of students in stem at from this dataset was 86%. I used pivot_longer with summarize to view the mean costs of room/board, books, and personal expenses grouped by each state. I used pivot_wider to view the minimum out-of-state tuition for private vs. public schools in each state. *

### Visualizing

##### Correlation heatmap
```{R}
cormat2 <- merged_data2 %>% select_if(is.numeric) %>% cor(use="pair")

tidycor2 <- cormat2 %>% as.data.frame %>% rownames_to_column("Variable_1") %>% pivot_longer(-1, names_to="Variable_2", values_to="Correlation")

tidycor2 %>% ggplot(aes(Variable_1, Variable_2, fill=Correlation)) + geom_tile() + scale_fill_gradient2(low="red", mid="white", high="blue") + geom_text(aes(label=round(Correlation,2)), color="black", size=1) + coord_fixed() + theme(axis.text.x = element_text(angle=90, hjust=1))
```
*Early career pay rate is very positively correlated with mid career pay, as expected. Number of new students enrolled is very positively correlated with both acceptance rate and the number of full time undergraduates. Number of new students from the top 25% of class is very positively correlated with the number of new students from top 10%, but this was also expected. To mention some of the negative correlations, student/faculty ratio is negatively correlated with the school's educational expenditure per student which makes sense. Out-of-state tuition was also negatively correlated with student/faculty ratio. There is no correlation between book costs and the percent of alumni who donate. There is also no correlation between the number of students from the top 10% of their HS class and the number of full time undergraduates.*

##### Plot 1
```{R}
colors <- c("No"="darkgreen","Yes"= "turquoise")

merged_data2 %>% ggplot(aes(make_world_better_percent, mid_career_pay,color=Private)) + geom_point() + 
  labs(title = "Mid-career pay vs. % of alumni who think they're improving the world", x="% of alumni who think they're making world a better place", y="Estimated mid career pay ($)") + 
  theme_minimal() + 
  scale_color_manual(values=colors) + 
  scale_y_continuous(breaks = seq(0,160000,10000)) + 
  scale_x_continuous(breaks = seq(0,100,10)) + 
  theme(axis.line = element_line(color = "black", size = 0.5)) + 
  theme(axis.text = element_text(color="black")) 
  
```

*This plot illustrates that the highest estimated mid-career pay rates are mostly found from students at private universities. Private schools also had the highest percentages of alumni who think they're making the world a better place. However, this could be simply because this dataset contains more private schools than public schools. There is not a super strong trend in this data, but interestingly, the schools with the highest percent of alumni who think they're improving the world corresponded to the lower estimated mid career pay rates.  But in general, as the percent of alumni who think they're improving the world increases, the estimated mid career pay does not increase.*

##### Plot 2
```{R}
merged_data2 %>% ggplot(aes(x=category_accept_rate, y=Apps, fill=Private)) + geom_bar(stat="summary", position="dodge") + 
  labs(title = "Applications received vs. acceptance rate quartile for private/public schools", x="Acceptance rate quartile", y="Applications received") + 
  theme_classic() + 
  scale_fill_brewer(palette="Spectral") + 
  theme(axis.text = element_text(color="black")) +
  theme(legend.background = element_rect(linetype = "solid", color = "black"))
```
*There were no public schools in this dataset with acceptance rates lower than 25%. Also, this plot shows that the number of applicants decreased as the acceptance rate increased. So schools with more applicants were more selective and had lower acceptance rates, which makes sense because they cannot accept everyone even though many people want to attend these "top tier" schools. Similarly, schools with few applicants had high acceptance rates - either because the school needs students or because students do not want to attend a school that's "easy" to get into. For example, private schools with very high acceptance rates had very few applicants. In quartiles 2,3, and 4 public schools had more applicants than private schools. *

### Dimensionality Reduction
```{R}
cluster_data <- merged_data2 %>% select(-College_name, -Private, -state_name, -category_accept_rate) %>% scale()

silhouette_width <- vector()
for(i in 2:10){  
  pam_fit <- pam(cluster_data, k=i)  
  silhouette_width[i] <- pam_fit$silinfo$avg.width  
}
ggplot() + geom_line(aes(x=1:10, y=silhouette_width)) + scale_x_continuous(name="k", breaks=1:10)

dist_mat <- merged_data2 %>% select(-Private, -state_name, -category_accept_rate) %>% mutate_if(is.numeric, scale) %>% column_to_rownames("College_name") %>% na.omit %>% dist %>% as.matrix

pam_result <- pam(dist_mat, k=2, diss=T)
dataset2 <- cbind(cluster_data, cluster = pam_result$cluster) %>% as.data.frame()

dataset2 %>% group_by(cluster) %>% summarize_if(is.numeric,mean,na.rm=T)

library(GGally)
ggpairs(dataset2, columns=c("Top10perc","Outstate","Expend","make_world_better_percent","mid_career_pay"), aes(color=as.factor(cluster)))

plot(pam_result, which=2)
```

*I first selected only the numeric columns from my dataset, scaled them, and named that data cluster_data. Then, I found out through the silhouette width that 2 clusters would be best for this data, as seen by the plot. I then made a distance matrix with the data, using Euclidean distances. PAM cluster analysis was then performed on the distance matrix and the cluster data was saved to the dataset, which I renamed as dataset2. I then found the cluster means to see which variables were important for differentiating the clusters. A GGally plot was then created using only 5 variables, because using 20+ variables would have been chaotic to visualize. As seen by the GGally plot, the data did not very cluster well. It seems that the Outstate variable separated the data the most. The average silhouette width was 0.19, meaning that no substantial structure was found. For some odd reason, the actual silhouette widths would not show up on the plot.*


...
